server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:



        #-----------service---------------------
          - id: security-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/keycloak/**
        #-----------service---------------------
          - id: menu-service
            uri: http://localhost:8099
            predicates:
              - Path=/api/menu/**
        #-----------Ged---------------------
          - id: Ged-Service
            uri: http://localhost:8088
            predicates:
              - Path=/api/file/**,/api/folder/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  instance:
    hostname: gateway-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

